import simtk.openmm.app
import simtk.openmm
from simtk.unit import *

import mdtraj as md
import numpy as np

import pymbar.timeseries
import matplotlib.pyplot as plt

def QuickTrim(prmtop, dcdIn, dcdOut=None, stride=1, plot=True):

    """A shortcut function that does what most users will want to do with this
        class. Uses most common options.

    Parameters
    ----------
    
    prmtop: str
             A list object containing the PRMTOPs of the systems for which RMSDS
             will be calculated
             
    dcdIn: list or str
             A DCD or a list of DCDs to be loaded into the prmtop

    stride: int, default=1
             Use this stride when loading the trajectories to sparsify the trajectories
             
    onlyProt: bool, default=True   
             If true, then load only the protein atoms. This saves memory, since most
             DCDs also contain more water atoms than protein atoms and often we want 
             the energy of the protein, without solvent contribution.
             
    plot: bool, default=True
            If True, then it will display the plot that would be generated by
            GenerateNEFFPlot.
            
    """

    InitTraj = DecorrelateTrajectory(prmtop=prmtop, DCDS=dcdIn, stride=stride)
    InitTraj.GetPotentialEnergies()
    InitTraj.TimeseriesDecorrelation()
    
    if (plot == True):
        InitTraj.GenerateNEFFPlot()
     
    InitTraj.GetDecorrSamples()
     
    TrimmedTraj = InitTraj.TrimTraj(dcdOut=dcdOut)
    
    return(TrimmedTraj)